Update license to the one UCLA uses
UCLALibrary/prl-harvester pull request #4
Opened 2022-08-23 21:45 UTC by ksclarke

This commit also serves to trigger the build (and later release) Actions
to confirm that the repository's secrets are setup correctly.

2022-08-23 22:01 UTC, DRickard approved these changes

2022-08-23 22:16 UTC, markmatney commented
Should we have a copy of the license in the repo as well, since our other projects do?

2022-08-24 14:05 UTC, ksclarke commented
> Should we have a copy of the license in the repo as well, since our other projects do?

Yes, good catch. Added.

2022-08-24 14:54 UTC, DRickard submitted a review, later dismissed

2022-08-24 16:52 UTC, markmatney requested changes

2022-08-24 16:52 UTC, markmatney commented on LICENSE.txt
> +Copyright (c) 2019, The Regents of the University of California
```suggestion
Copyright (c) 2022, The Regents of the University of California
```

2022-08-24 16:56 UTC, markmatney approved these changes

2022-08-24 17:49 UTC, merged